# Generated by Django 3.0.5 on 2022-11-17 08:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle_mode',
            fields=[
                ('battle_mode_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('battle_mode_name', models.CharField(help_text='バトルモード', max_length=30)),
            ],
            options={
                'db_table': 'battle_mode',
            },
        ),
        migrations.CreateModel(
            name='Kurabeteminaika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('weapon_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('weapon_name', models.CharField(help_text='武器名', max_length=30)),
            ],
            options={
                'db_table': 'weapon',
            },
        ),
        migrations.CreateModel(
            name='Match_result',
            fields=[
                ('match_result_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.BooleanField(help_text='勝利した場合はTrue')),
                ('battle_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurabeteminaika.Battle_mode')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurabeteminaika.Weapon')),
            ],
            options={
                'db_table': 'match_result',
            },
        ),
    ]
