# Generated by Django 3.0.5 on 2022-11-03 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurabeteminaika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='special_weapon',
            fields=[
                ('special_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('special_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sub_weapon',
            fields=[
                ('sub_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='weapon_category',
            fields=[
                ('category_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='weapon_configuration',
            fields=[
                ('weapon_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('weapon_name', models.CharField(max_length=50)),
                ('range', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('fire_rate', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurabeteminaika.weapon_category')),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurabeteminaika.special_weapon')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurabeteminaika.sub_weapon')),
            ],
        ),
    ]
